title: Sumo Testing

shared_settings:
  scratch_ensembles:
    DUMMY_SUMO_ITER: ../webviz-subsurface-testdata/01_drogon_ahm/realization-*/iter-0

options:
  menu:
    initially_pinned: True

layout:
  - page: Sumo Test
    content:
      - MapViewerSUMO:
          field_name: DROGON
          ensembles:
            21.x.0.dev_2022-03-17_DEMO: [0]
            21.x.0.dev_2022-05-27_adnj_01: [0]

  # - page: Sumo Test 2
  #   content:
  #     - MapViewerSUMO:
  #         field_name: DROGON
  #         ensembles:
  #           21.x.0.dev_2022-03-17_DEMO: [0]
  #           21.x.0.dev_2022-05-27_adnj_01: [0]
